parameters:
  - name: repoName
    type: string

steps:
- pwsh: '$(scriptsDirectory)/clean-java-files.ps1'
  displayName: 'Remove generated models and requests from the repo'
  env:
    MainDirectory: $(Build.SourcesDirectory)/${{ parameters.repoName }}/src/main/

- pwsh : $(Build.SourcesDirectory)/${{ parameters.repoName }}/Scripts/incrementMinorVersion.ps1
  displayName: 'Increment minor version number'
  workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.repoName }}/Scripts'

- pwsh: '$(scriptsDirectory)/copy-java-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/output
    RepoModelsDir: $(Build.SourcesDirectory)/${{ parameters.repoName }}/